### ISSUE TITLE
Query Regarding a Potential Typo in the Narcissus.ipynb File

### ISSUE THREAD

**Issue by LandAndLand** [ruoxi-jia-group/Narcissus-backdoor-attack#4]
I've been using your ipynb file recently and came across a minor confusion that I haven't seen discussed anywhere else. I thought I'd bring it up here and ask for clarification, in case I've misunderstood something. I hope you won't mind my question! 
![image](https://github.com/ruoxi-jia-group/Narcissus/assets/32730843/205701c9-e9a6-4dd2-8d7a-dc3e34300fbb)

**Comment by pmzzs** [comment]
You can remove this step since in the next line we clean the gradient in the optimizer, sorry for the repeat code.

**Comment by LandAndLand** [comment]
Thank you for your response!
